name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Code static analysis
      run: platformio check

    - name: Run PlatformIO build on selected platforms
      run: platformio run -e esp32dev

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .pio/build/esp32dev/firmware.bin
        asset_name: firmware.bin
        tag: ${{ github.ref }}
        overwrite: true